---
- name: Disable root logins
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^PermitRootLogin'
    line: 'PermitRootLogin no'

- name: Set AllowUsers
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^AllowUsers'
    line: 'AllowUsers {{ sshd_config_allow_users }}'
  when:
    - sshd_config_allow_users is defined

- name: Disable Protocol 1
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^Protocol (\d,?)+'
    line: 'Protocol 2'

- name: Disable Password Authentication
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^PasswordAuthentication no'
    line: 'PasswordAuthentication no'
 
- name: Set SSH port
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^Port \d+'
    line: 'Port {{ sshd_port }}'

- name: Allow SSHD to listen on tcp port
  seport:
    ports: '{{ sshd_port }}'
    proto: tcp
    setype: ssh_port_t
    state: present

- name: Install FirewallD
  yum:
    name: firewalld
    state: latest

- name: Enable & start FirewallD
  systemd:
    name: firewalld
    state: started
    enabled: yes

- name: Open new SSH port
  firewalld:
    port: '{{ sshd_port }}/tcp'
    permanent: true
    state: enabled
