---
- hosts: all
  tasks:
    - name: Disable root logins
      become: true
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^PermitRootLogin'
        line: 'PermitRootLogin no'

    - name: Set AllowUsers
      become: true
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^AllowUsers'
        line: 'AllowUsers {{ sshd_config_allow_users }}'

    - name: Disable Protocol 1
      become: true
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^Protocol (\d,?)+'
        line: 'Protocol 2'

    - name: Disable Password Authentication
      become: true
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^PasswordAuthentication no'
        line: 'PasswordAuthentication no'
 
    - name: Set SSH port
      become: true
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^Port \d+'
        line: 'Port {{ ansible_port }}'

    - name: Open new SSH port
      become: true
      firewalld:
        port: '{{ ansible_port }}/tcp'
        permanent: true
        state: enabled
    
    - name: Enable & start FirewallD
      become: true
      systemd:
        name: firewalld
        state: started
        enabled: yes

