---
- hosts: all
  tasks:
    - name: Update yum
      become: true
      yum: state=latest name='*'

    - name: Install base yum packages
      become: true
      yum:
        name:
          - NetworkManager
          - git
          - vim
          - epel-release

    - name: Install pip
      become: true
      yum: name=python-pip

    - name: install OpenShift pip dependencies
      become: true
      pip:
        name:
          - cryptography
          - pyOpenSSL
          - lxml
          - passlib

    - name: Ensure NetworkManager is enabled & started
      become: true
      systemd:
        name: NetworkManager
        state: started
        enabled: yes

    - name: Ensure SELINUX=enforcing
      become: true
      lineinfile:
        path: /etc/selinux/config
        regexp: '^SELINUX='
        line: 'SELINUX=enforcing'

    - name: Increase soft & hard file limits to 64k
      become: true
      lineinfile:
        path: /etc/sysctl.conf
        line: 'fs.file-max = 64000'

    - name: Increase nofile limit to 64k
      become: true
      lineinfile:
        path: /etc/security/limits/conf
        line: '* - nofile 64000'

    - name: Restart Sysctl
      become: true
      shell: sysctl -p
